api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/php"
  id = "initializ-buildpacks/php"
  name = "Initializ Buildpack for PHP"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/php/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.3"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.14"

  [[order.group]]
    id = "initializ-buildpacks/php-dist"
    version = "3.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer-install"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/httpd"
    version = "0.7.22"

  [[order.group]]
    id = "initializ-buildpacks/php-fpm"
    version = "0.2.24"

  [[order.group]]
    id = "initializ-buildpacks/php-httpd"
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-memcached-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-redis-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-start"
    version = "2.0.0"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.20"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.13"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.3"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.14"

  [[order.group]]
    id = "initializ-buildpacks/php-dist"
    version = "3.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer-install"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/nginx"
    version = "0.15.22"

  [[order.group]]
    id = "initializ-buildpacks/php-fpm"
    version = "0.2.24"

  [[order.group]]
    id = "initializ-buildpacks/php-nginx"
    version = "0.3.18"

  [[order.group]]
    id = "initializ-buildpacks/php-memcached-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-redis-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-start"
    version = "2.0.0"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.20"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.13"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/php-dist"
    version = "3.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/composer-install"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-builtin-server"
    version = "0.4.35"

  [[order.group]]
    id = "initializ-buildpacks/php-memcached-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/php-redis-session-handler"
    optional = true
    version = "1.0.0"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.20"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.13"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.0"
